### ISSUE TITLE
Can't override/localise the search placeholder text

### ISSUE THREAD

**Issue by DLatheron** [jyotirmaybanerjee/react-duallist#3]
The string for the placeholder test for the left and right search boxes appears to be fixed in Index.js, lines 235 and 294.

It would be really useful to make this externally accessible because currently a library user can change the props for the left and right labels, but can't keep the search text in sync with these names.

I'm happy to submit a PR for the change if you don't have time.

**Comment by jyotirmaybanerjee** [comment]
@DLatheron Please feel free to create the PR. I'll be happy to merge that.

**Comment by DLatheron** [comment]
Cheers!

I've got the change on a local branch, but I don't have permissions to create a branch (and therefore a PR) in your repository. How do you want to do this?

**Comment by DLatheron** [comment]
@jyotirmaybanerjee I have merged this - can you push the latest to NPM please?

**Comment by DLatheron** [comment]
Fix made - but needs to be published :-)

**Comment by jyotirmaybanerjee** [comment]
Done. :)

**Comment by DLatheron** [comment]
Cheers!
