### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by risaac** [jyotirmaybanerjee/react-duallist#7]
Hi Jyotirmay,

Thanks for the great library. I wanted to see if it was possible for you to expose additional properties. 

1. The ability change the placeholder text in the search inputs.
2. Add Labels underneath each of the list boxes

Best,

Roberto

**Comment by DLatheron** [comment]
Hi Roberto,

I merged a change that did number 1.

Dave

**Comment by risaac** [comment]
@DLatheron Thank you!!!  Number 2 is a is a nice to have but, not necessary.
